name: CraftFortress2
main: org.github.craftfortress2.CraftFortress2
version: 0.02_ALPHA

commands:
  cfstart:
    description: Force starts the game.
    usage: /cfstart
    permission: cf.start
    permission-message: You don't have permission!
  cfend:
    description: Force ends the game.
    usage: /cfend
    permission: cf.end
    permission-message: You don't have permission!
  cfhelp:
    description: Prints out help.
    usage: /cfhelp
    permission: cf.help
    permission-message: You don't have permission!
  cfjoin:
    description: Join the game.
    usage: /cfjoin <team> <class>
    permission: cf.join
    permission-message: You don't have permission!
  cfclass:
    description: Change class
    usage: /cfclass <class>
    permission: cf.class
    permission-message: You don't have permission!

permissions:
  cf.*:
    description: Gives access to all CraftFortress2 commands
    children:
      cf.start: true
      cf.end: true
      cf.help: true
      cf.join: true
      cf.class: true
    cf.start:
      description: Allows you to force start the game.
      default: op
    cf.end:
      description: Allows you to force end the game.
      default: op
    cf.help:
      description: Allows you to view help.
      default: true
    cf.join:
      description: Allows you to join the game.
      default: true
    cf.class:
      description: Allows you to change classes.
      default: true